### ISSUE TITLE
Travis build failing - libgfortran related?

### ISSUE THREAD

**Issue by sonyahanson** [choderalab/assaytools#119]
Seems like the travis build is currently failing, potentially because of this line in our conda recipe:
`    - libgfortran ==1.0.0 [linux]`

This is the commit that changed this: https://github.com/choderalab/assaytools/commit/8e6f35eb7bbcf237386248f054a46b2fed1cc90a

Seems like we are no longer pinning the pymc version. Do we have to keep this libgfortran version pinned for some other reason?

**Comment by bas-rustenburg** [comment]
The commit you point to pins pymc, and gfortran.

This one unpins only pymc. Has it been broken for that long,, or did something else change too?


https://github.com/choderalab/assaytools/commit/7adbe6e0deb191cf88aaaebd8aa500fc1d93fc61#diff-23fca1736cbf667a8319e570051bbe20

**Comment by MehtapIsik** [comment]
This problem looks similar to assaytools installation problems I have been having, because of pymc dependency.
The combination of versions that worked for me in the end is:
```
pymc                      2.3.6 
libgfortran               3.0.0  
gcc                       4.8.5 
libgcc                    5.2.0           
```

**Comment by sonyahanson** [comment]
I wonder if @jchodera noticed if this was happening when he cut a release in June: https://github.com/choderalab/assaytools/pull/111

**Comment by bas-rustenburg** [comment]
It looks like that PR might have been merged before the travis tests had a chance to run, which would lead to the travis logs you see there.

**Comment by jchodera** [comment]
Looks like this is because `libgfortran 1.0` has been removed from standard channels. Now that we're requiring `conda-forge`, we need to:
* Add `conda-forge` to the channels in `.travis.yaml` according to [these instructions](http://www.omnia.md/install/):
```bash
conda config --add channels omnia --add channels conda-forge
```
This should cause `pymc` to be picked up from `conda-forge`
* Remove the `libgfortran` explicit dependency in `devtools/conda-recipe/meta.yaml`, since I don't think this should be explicitly specified anymore; we should rely on the `conda-forge` `pymc` to include its own dependencies.
